name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  PYTEST_FLAGS: --cov=stardis --cov-report=xml --cov-report=html --stardis-regression-data=${{ github.workspace }}/stardis-regression-data
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    # if: github.repository_owner == 'tardis-sn'
    strategy:
      matrix:
        include:

        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/stardis

        # - os: ubuntu-latest
        #   label: linux-64-cuda
        #   prefix: /usr/share/miniconda3/envs/stardis

        - os: macos-latest
          label: osx-64
          prefix: /Users/runner/miniconda3/envs/stardis
    
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
    
      - name: Setup LFS
        uses: ./.github/actions/setup_env

      - name: Install TARDIS
        id: install-tardis
        run: |
          pip install git+https://github.com/tardis-sn/tardis.git@release-2024.08.25
          
      - name: Install STARDIS
        id: install-stardis
        run: |
          pip install -e .[test]
          
      - name: Run tests
        run: pytest ${{ env.PYTEST_FLAGS }}          

      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
